# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(402, 337)
        self.Start = QtWidgets.QPushButton(Dialog)
        self.Start.setGeometry(QtCore.QRect(10, 10, 381, 71))
        self.Start.setAutoFillBackground(False)
        self.Start.setObjectName("Start")
        self.Cancel = QtWidgets.QPushButton(Dialog)
        self.Cancel.setGeometry(QtCore.QRect(10, 90, 381, 71))
        self.Cancel.setObjectName("Cancel")
        self.Sent = QtWidgets.QPushButton(Dialog)
        self.Sent.setGeometry(QtCore.QRect(10, 170, 381, 71))
        self.Sent.setObjectName("Sent")
        self.Screenshot = QtWidgets.QPushButton(Dialog)
        self.Screenshot.setGeometry(QtCore.QRect(10, 250, 381, 71))
        self.Screenshot.setObjectName("Screenshot")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.Start.setText(_translate("Dialog", "ON"))
        self.Cancel.setText(_translate("Dialog", "OFF"))
        self.Sent.setText(_translate("Dialog", "SENT"))
        self.Screenshot.setText(_translate("Dialog", "SCREENSHOT"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
